<template>
  <!-- [ldio] generated by https://loading.io/ -->
  <component
    is="svg"
    v-bind="$props"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <circle
      cx="50"
      cy="50"
      r="30"
      stroke-width="8"
      :stroke="stroke"
      stroke-dasharray="47.12388980384689 47.12388980384689"
      fill="none"
      stroke-linecap="round"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        repeatCount="indefinite"
        dur="1.1363636363636365s"
        keyTimes="0;1"
        values="0 50 50;360 50 50"
      ></animateTransform>
    </circle>
  </component>
</template>

<script>
export default {
  name: "DualRing",
  props: {
    width: {
      type: [Number, String],
      default: "100%",
    },
    height: {
      type: Number,
      default: 50,
    },
    stroke: {
      type: String,
      default: "#000",
    },
  },
};
</script>
